server:
  host: "localhost"
  port: 50052

ai:
  sys_promt_path: "./config/prod.promt.txt"
  model: "deepseek-v3"
  image_model: "flux-dev"
  retry_policy:
    timeout: 30
    image_timeout: 999
    retry_count: 3
    retry_timeout: 1

logging:
  level: "DEBUG"
  in_file: false
