server:
  host: "localhost"
  port: 50050
  grace_time: 600

ai:
  sys_promt_path: "./config/prod.promt.txt"
  text_generation:
    model: "deepseek-v3"
    providers: "LambdaChat,PollinationsAI,Blackbox"
  image_model: "flux-dev"
  retry_policy:
    timeout: 30
    image_timeout: 999
    retry_count: 3
    retry_timeout: 1

logging:
  level: "DEBUG"
  in_file: false
