server:
  host: "0.0.0.0"
  port: 50051
  grace_time: 600

ai:
  sys_promt_path: "./config/prod.promt.txt"
  text_generation:
    model: "deepseek-v3"
    providers: "LambdaChat,PollinationsAI,Blackbox"
  image_model: "flux-dev"
  retry_policy:
    timeout: 40
    image_timeout: 180
    retry_count: 5
    retry_timeout: 5

logging:
  level: "INFO"
  in_file: true