server:
  host: "localhost"
  port: 50051

ai:
  model: "deepseek-v3"
  image_model: "flux-dev"
  retry_policy:
    timeout: 40
    image_timeout: 180
    retry_count: 5
    retry_timeout: 5

logging:
  level: "INFO"
  in_file: true